#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# source aliases
ALIASFILE=~/.zsh_aliases
source $ALIASFILE
function add_alias() {
    if [[ -z $1 || -z $2 || $# -gt 2 ]]; then
        echo usage:
        echo "\t\$$0 ll 'ls -l'"
    else
        echo "alias $1='$2'" >> $ALIASFILE
        echo "alias ADDED to $ALIASFILE"
    fi
}

# Customize to your needs...
export WORKON_HOME=$HOME/Software/.virtualenvs
export PROJECT_HOME=$HOME/Software/git
export EDITOR=vim
source /usr/local/bin/virtualenvwrapper.sh
setopt noclobber
export PYENV_ROOT="$HOME/.pyenv"
eval "$(pyenv init -)"
export PATH="$PYENV_ROOT/bin:$PATH:$HOME/go/bin:$HOME/.cargo/bin"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform
